config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'index', to: 'pages#index'
  get 'activites', to: 'pages#activites'
  get 'references', to: 'pages#references'
  get 'evenements', to: 'pages#evenements'
  get 'documents', to: 'pages#documents'
  get 'about_us', to: 'pages#about_us'
  get 'contact', to: 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # test with top navbar
  get 'home_test', to: 'pages#home_test'

  # test with top navbar
  get 'home_portfolio', to: 'pages#home_portfolio'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index, :activites, :references, :evenements, :documents, :about_us, :contact, :home_test, :home_portfolio]

  def home
  end

  def index
  end

  def activites
  end

  def references
  end

  def evenements
  end

  def documents
  end

  def about_us
  end

  def contact
  end

  def home_test
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PHUNG Consulting</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
  </head>
  <body>
    <% unless current_page?(root_path) %>
      <div class="main-page">
        <%= render 'shared/home-navbar' %>
    <% end %>

      <%= render 'shared/flashes' %>
      <%= yield %>

    <% unless current_page?(root_path) %>
      </div>
    <% end %>

    <% if current_page?(home_portfolio_path) %>
      <div id="credit-footer">
        <%= render 'shared/footer' %>
      </div>
    <% end %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>AOS.init();</script>
  </body>
</html>

app/views/pages/about_us.html.erb
<div class="section-container">
  <h1>Climatic, electric, energetic and environmental engineering</h1>

  <div class="title pt-4">
    <h2>presentation of the company</h2>
  </div>

  <div class="text pt-4">
    <p>In the field of Thermal Environment (Heating, Ventilation, Air-conditioning and Smoke clearing) and of Sanitary Facilities (Plumbing), I am able to propose all the missions including the control of design from the feasibility of a project until the delivery of a job.</p>
    <p class="pt-4">According to the complexity of the project and the wishes of the customer, the missions can be declined as follows:</p>
    <ul>
      <li>Studies of programming defining the needs of the users of buildings;</li>
      <li>Audits and thermal diagnoses of the existing buildings;</li>
      <li>Recommendations in the technico-economic field and studies (investment, exploitation, profitability);</li>
      <li>Outline project with pilot study of various possible solutions;</li>
      <li>Estimate or detailed figuring of the labor costs;</li>
      <li>Assistance with the architect for the deposit of a permit building or a declaration of work;</li>
      <li>Assistance with the deposit of a declaration of installation classified for environmental protection (boiler room, refrigerating production…) ;</li>
      <li>Summary preliminary draft for definition of the services;</li>
      <li>Detailed preliminary draft for the dimensioning of the installations;</li>
      <li>File-project and Tender documents of the companies;</li>
      <li>Assistance in the making of the markets with comparative analysis of the estimates of companies;</li>
      <li>Control of the execution documents of the companies;</li>
      <li>Control of the works in course of execution;</li>
      <li>Works preliminary to the reception;</li>
      <li>Finalization of the works of the companies;</li>
      <li>H.Q.E. steps
    </ul>
    <p>My skills are particularly orientated towards the global or partial construction or restoration of tertiary, industrial or residential buildings, such as buildings of offices, residences hotel, shops and banking agencies, space of exposure and museographic.</p>
    <p class="pt-4">I’m working for building owners, patrimonial investors, property developers, project superintendents, architects, or contractors in important research departments.</p>
    <p>My activity is covered by a professional insurance EUROMAF (Mutual of the French Architect).</p>
    <p class="pt-4">My recent achievements are inter alia:</p>
    <ul>
      <li>New building of the Offices and Workshops of 14.000 m ² with certification HQE and THPE in Paris (75013) for Real Vinci;</li>
      <li>Banking agencies CIC and Mutual credits (37 agencies treated from 150 to 300 m ² by agency) at Paris and Ile de France for the Banks CIC IDF and Mutual credit;</li>
      <li>Construction of the space of Temporary exhibition to the Museum of Pierre with Saint Maximim for the Town of Maximim Saint;</li>
      <li>Repair of 7 sub-stations in the Clairval Institute in Bièvres for ESSOR</li>
      <li>Installation of a space museographic of 2.000 m ² in two old lace manufactures to the Museum of lace with Retournac (43130) for the Town of Retournac;</li>
      <li>Design engineering of a new building of a hotel controls in France of 110 rooms of the new concept “Continuation hotel” of 3.000 m ² (with project of international establishment) for Group ACCOR;</li>
      <li>Feasibility study of the heat pump on ground water of the site of maintenance and putting up of tramway T2 of 3 700 m² in Colombes for the RATP</li>
    </ul>
    <p>Feasibility study of the heat pump on vertical probes for the transformation of the Manor of Sauvegrain (classified building) into hotel 3 stars of 1.300 m ² to St Lambert of Wood (78) for the Association of November 23.</p>
    <p class="pt-4">Studies in the thermics for ten projects mainly in Ile de France:</p>
    <ul>
      <li>Eurosquare Bureaux of 15.000 m2 to St Ouen;</li>
      <li>Biopark - 2 biotechnic buildings Offices and 3 buildings - 30.000 m2 in Paris 13th;</li>
      <li>Project Sun & Moon - 14 buildings of residences haussmanniens of approximately 50.000 m2 located at the République avenue in Marseilles;</li>
      <li>Foundry Manor Industries 46.000 m2 with Outreau;</li>
      <li>Hotel Ambassador - 16 Bd Haussmann in Paris;</li>
      <li>Office building of 5.000 m2 with Charenton-the-Bridge;</li>
      <li>Office buildings 5.000 and 7.000 m2 with 5/7 rue Scribe in Paris;</li>
      <li>Office building - 16 rue Washington in Paris;</li>
      <li>Office building - Turn Eurocity III - Avenue Willy BRANDT in Lille.</li>
    </ul>
  </div>
</div>

app/views/pages/activites.html.erb
<div class="section-container">
  <h1>Ingénierie en génie climatique, électrique,
  énergétique et environnemental</h1>

  <div class="title pt-4">
    <h2>activités - domaines</h2>
    <p>Etudes de conception depuis l'avant projet jusqu'au dossier d'appel d'offres et suivi de chantier</p>
  </div>

  <div class="text pt-4">
    <h2>Nos domaines</h2>
    <p>Réalisation des installations en génie climatique, en plomberie-sanitaire et en éléctricité</p>
  </div>

  <div class="text pt-4">
    <h2>Nos missions</h2>
    <p>Assistance à la maitrise d'ouvrage : accompagnement de la conception du projet à l'explotation du site</p>
    <p>Maitrise d'œuvre : suivi des projets depuis le concours jusqu'à la réception du chantier</p>
  </div>

  <div class="text pt-4">
    <h2>Notre secteur d'activité</h2>
    <p>Batiments tertiaires industriels ou résidentiels et collectifs</p>
  </div>

  <div class="text pt-4">
    <h2>Notre philosophie</h2>
    <p>Solution sur mesure, respect des délais, des coûts et de l'impact environnemental.</p>
  </div>

</div>

app/views/pages/contact.html.erb
<div class="section-container">
  <h1>Ingénierie en génie climatique, électrique,
  énergétique et environnemental</h1>

  <div class="title pt-4">
    <h2>contact</h2>
  </div>

  <div class="text pt-4">
    <h2>Bureau d'études fluides</h2>
    <p>110, rue de Fontenay 94300 Vincennes</p>
    <p>tél : +33 (0)1 48 59 12 96</p>
    <p>email : contact@phungconsulting.fr</p>
  </div>

</div>

app/views/pages/documents.html.erb
<div class="section-container">
  <h1>Ingénierie en génie climatique, électrique,
  énergétique et environnemental</h1>

  <div class="title pt-4">
    <h2>documents</h2>
    <p class="pt-4">
      <%= link_to "/pdf/presentation.pdf", target:"_blank", class:"" do %>
        Présentation
      <% end %>
    </p>
    <p>
      <%= link_to "/pdf/moyens_bet.pdf", target:"_blank", class:"" do %>
        Moyens société
      <% end %>
    </p>
    <p>
      <%= link_to "/pdf/references2016.pdf", target:"_blank", class:"" do %>
        Références Phung Consulting
      <% end %>
    </p>
  </div>
</div>

app/views/pages/evenements.html.erb
<div class="section-container">
  <h1>Ingénierie en génie climatique, électrique,
  énergétique et environnemental</h1>

  <div class="text text-center pt-5">
    <p class="text pb-2 text-center">Vœux 2020</p>
    <%= image_tag "phung_voeux20.jpg", alt: "Bonne année 2020", class:"event-picture" %>
  </div>

  <div class="text text-center pt-4">
    <p class="text pb-2 text-center">Vœux 2019</p>
    <%= image_tag "phung_voeux19.jpg", alt: "Bonne année 2019", class:"event-picture" %>
  </div>

  <div class="text pt-4 text-center pb-2">
    <p class="text pb-2">Vœux 2018</p>
    <%= image_tag "phung_voeux18.jpg", alt: "Bonne année 2018", class:"event-picture" %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">

  <div class="home d-flex align-items-center justify-content-center flex-column">
    <%= link_to home_test_path do %>
      <div class="text-center py-xl-5 my-xl-5 py-lg-4 my-lg-4 py-md-3 my-md-3 py-sm-2 my-sm-2">
        <%= image_tag "logo.png", alt: "logo" %>
        <p style="font-family: serif; color: #808080; font-size: 22px">Bureau d'études fluides</p>
      </div>
    <% end %>
    <div class="text-center">
      <div id="home-carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag "banner/banner1.jpg", alt: "First banner", class:"d-block home-banner" %>
          </div>
          <div class="carousel-item">
            <%= image_tag "banner/banner2.jpg", alt: "Second banner", class:"d-block home-banner" %>
          </div>
          <div class="carousel-item">
            <%= image_tag "banner/banner3.jpg", alt: "Third banner", class:"d-block home-banner" %>
          </div>
          <div class="carousel-item">
            <%= image_tag "banner/banner4.jpg", alt: "Fourth banner", class:"d-block home-banner" %>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/pages/home_portfolio.html.erb
<div class="master-banner" id="master-banner">
  <div class="container text-center">
      <p data-aos="fade-down-right" data-aos-duration="3000">Phung Consulting</p>
      <p data-aos="fade-down-right" data-aos-duration="3000" data-aos-delay="3000">Ingénierie en génie climatique, électrique, énergétique et environnemental</p>
      <br><%= link_to "Contact", "#social-footer", class:"btn btn-success px-5"  %>
  </div>
</div>

<div class="py-5" id="text">
  <div class="container">
    <h2>Climatic, electric, energetic and environmental engineer</h2>
    <div class="row">
      <div class="col-12 col-lg-6 py-lg-2 bg-white">
        <p>In the field of Thermal Environment (Heating, Ventilation, Air-conditioning and Smoke clearing) and of Sanitary Facilities (Plumbing), I am able to propose all the missions including the control of design from the feasibility of a project until the delivery of a job.</p>
        <p class="pt-4">According to the complexity of the project and the wishes of the customer, the missions can be declined as follows:</p>
        <ul>
         <li>Studies of programming defining the needs of the users of buildings;</li>
         <li>Audits and thermal diagnoses of the existing buildings;</li>
         <li>Recommendations in the technico-economic field and studies (investment, exploitation, profitability);</li>
         <li>Outline project with pilot study of various possible solutions;</li>
        </ul>
      </div>
      <div class="col-12 col-lg-6 py-lg-2 bg-white">
        <ul>
           <li>Estimate or detailed figuring of the labor costs;</li>
           <li>Assistance with the architect for the deposit of a permit building or a declaration of work;</li>
           <li>Assistance with the deposit of a declaration of installation classified for environmental protection (boiler room, refrigerating production…);</li>
          <li>Summary preliminary draft for definition of the services;</li>
          <li>Detailed preliminary draft for the dimensioning of the installations;</li>
          <li>File-project and Tender documents of the companies;</li>
          <li>Assistance in the making of the markets with comparative analysis of the estimates of companies;</li>
          <li>Control of the execution documents of the companies;</li>
          <li>Control of the works in course of execution;</li>
          <li>Works preliminary to the reception;</li>
          <li>Finalization of the works of the companies;</li>
          <li>H.Q.E. steps</li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="secondary-banner" id="secondary-banner">
  <div class="container container-home text-center">
    <h2> Want to work with us?</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit architecto rerum vitae laboriosam illo soluta, amet maiores fugiat qui animi natus corporis adipisci, impedit non labore quas! Odio, hic, sint!</p>
    <%= link_to "Click here", "", class:"btn btn-success"  %>
  </div>
</div>

<div id="portfolio-links">
  <%= render 'shared/portfolio-links' %>
</div>

<div id="tabs">
  <%= render 'shared/tabs' %>
</div>

<div id="assets">
  <%= render 'shared/assets' %>
</div>

<div class="py-5" id="cards">
  <div class="container container-home text-center">
    <h2> Les Références de Phung Consulting</h2>
    <div class="cards">
      <% @url_image_path = "https://source.unsplash.com/random/200x200" %>
      <%= render "shared/vertical-card" %>
      <% @url_image_path = "https://source.unsplash.com/random/200x199" %>
      <%= render "shared/vertical-card" %>
      <% @url_image_path = "https://source.unsplash.com/random/199x199" %>
      <%= render "shared/vertical-card" %>
    </div>
  </div>

</div>

<div style="background-color: white" class="py-5" id="collaborate-section">
  <div class="container container-home">
    <h2 class="text-center"> Une question? Envie de collaborer?</h2>
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <p>Contactez Lydie PHUNG, gérante</p>
        <p style="margin:0px"><small>Code APE/NAF : 7112 B - Ingénierie, études techniques</small></p>
        <p style="margin:0px"><small>N° SIREN : 492 583 539 RCS Créteil</small></p>
        <p style="margin:0px"><small>EURL au capital de 30 000€</small></p>
        <p style="margin:0px"><small>TVA : FR 55 49 25 83 53 – TVA sur encaissement</small></p>
        <p style="margin:0px"><small>EUROMAF-ID : 7383027/E/10 - N° POLICE : 7003094/S</small></p>
      </div>
    </div>
  </div>
</div>

<div style="" class="py-5">
  <div class="container container-home">
    <h2 class="text-center"> Venez nous rencontrer</h2>
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <p>Bureaux :</p>
        <p>110, rue de Fontenay 94300 Vincennes</p>
        <p>Tél : <%= link_to "+33 (0)1 48 59 12 96", "tel:+33 (0)1 48 59 12 96" %></p>
        <p>email : <%= link_to "contact@phungconsulting.fr", "mailto:contact@phungconsulting.fr"  %></p>
      </div>
    </div>
  </div>
</div>

<div id="social-footer">
  <%= render 'shared/social-links' %>
</div>

<div id="master-footer">
  <%= render 'shared/master-footer' %>
</div>

app/views/pages/references.html.erb
<div class="section-container">
  <h1>Ingénierie en génie climatique, électrique,
  énergétique et environnemental</h1>

  <div class="title pt-4">
    <h2>principales références</h2>
    <%= link_to "/pdf/references2016.pdf", target:"_blank", class:"btn btn-primary" do %>
      Téléchargez le PDF
    <% end %>
  </div>

  <div class="reference-categories pt-4">
    <div>
      <p>Audits</p>
      <%= image_tag "audits.jpg", alt: "audits", class:"reference-picture" %>
    </div>
    <div>
      <p>Logements</p>
      <%= image_tag "logements.jpg", alt: "logements", class:"reference-picture" %>
    </div>
    <div>
      <p>Tertiaires</p>
      <%= image_tag "tertiaires.jpg", alt: "tertiaires", class:"reference-picture" %>
    </div>
  </div>

  <div class="text-center">
    <div id="reference-carousel" class="carousel slide pt-4 pb-2" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= image_tag "reference/reference1.jpg", alt: "First reference", class:"d-block reference-carousel" %>
        </div>
        <div class="carousel-item">
          <%= image_tag "reference/reference2.jpg", alt: "Second reference", class:"d-block reference-carousel" %>
        </div>
        <div class="carousel-item">
          <%= image_tag "reference/reference3.jpg", alt: "Third reference", class:"d-block reference-carousel" %>
        </div>
        <div class="carousel-item">
          <%= image_tag "reference/reference4.jpg", alt: "Fourth reference", class:"d-block reference-carousel" %>
        </div>
        <div class="carousel-item">
          <%= image_tag "reference/reference4.jpg", alt: "Fifth reference", class:"d-block reference-carousel" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_assets.html.erb
<div style="background-color: white" class="py-5">
  <div class="container-home text-center">
    <h2> Beautiful. Clean. Responsive.</h2>
    <div class="row justify-content-center" style="margin:0px">
      <div class="col-10 col-lg-3">
        <div class="asset">
          <div class="asset-img">
            <i class="far fa-heart"></i>
          </div>
          <div class="asset-text">
            <h2>Passion</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
          </div>
        </div>
      </div>
      <div class="col-10 col-lg-3">
        <div class="asset">
          <div class="asset-img">
            <i class="far fa-lightbulb"></i>
          </div>
          <div class="asset-text">
            <h2>Creativity</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
          </div>
        </div>
      </div>
      <div class="col-10 col-lg-3">
        <div class="asset">
          <div class="asset-img">
            <i class="far fa-star"></i>
          </div>
          <div class="asset-text">
           <h2>Quality</h2>
           <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div>Portfolio</div>
  <div>Follow me on social media</div>
</div>

app/views/shared/_home-navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-transparent justify-content-center container border-bottom">
    <div class="order-1 order-lg-1 order-xl-1 collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto selectors-test">
        <li class="nav-item">
          <div id="activites-selector" class="selector"> <p class="nav-link" >activités</p> </div>
        </li>
        <li class="nav-item">
          <div id="references-selector" class="selector"> <p class="nav-link" >références</p> </div>
        </li>
        <li class="nav-item">
          <div id="evenements-selector" class="selector"> <p class="nav-link" >événements</p> </div>
        </li>
      </ul>
    </div>

    <div class="order-2 order-lg-3 order-xl-3 collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <div id="documents-selector" class="selector"> <p class="nav-link" >documents</p> </div>
        </li>
        <li class="nav-item">
          <div id="about-us-selector" class="selector"> <p class="nav-link" >🇬🇧 about us</p> </div>
        </li>
        <li class="nav-item">
          <div id="contact-selector" class="selector"> <p class="nav-link" >contact</p> </div>
        </li>
    </div>

    <div class="order-3 order-lg-2 order-xl-2 d-flex flex-column">

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        Menu
      </button>

      <%= link_to home_test_path do %>
        <%= image_tag "logo.png", alt: "Phung Consulting Logo", class:"pt-1" %>
      <% end %>

    </div>
  </nav>

app/views/shared/_horizontal-card.html.erb
<div class="card-product my-3">
  <%= image_tag @url_image_path, alt: "logements", class:"reference-picture" %>
  <div class="card-product-infos">
    <h3 class="text-left"><%= @card_title %></h3>
    <p class="text-left">Quia quibusdam <strong>optio dignissimos incidunt porro</strong> !</p>
  </div>
</div>

app/views/shared/_master-footer.html.erb
<div style="background-color: #2B4155" class="py-5">
  <div class="container container-home">
    <div class="row justify-content-center">
      <div class="col-6 col-lg-3 py-2 text-white">
        <h2>WHO WE ARE</h2>
      </div>
      <div class="col-6 col-lg-3 py-2 text-white">
        <h2>LATEST WORKS</h2>
      </div>
      <div class="col-6 col-lg-3 py-2 text-white">
        <h2>GET IN TOUCH</h2>
      </div>
      <div class="col-6 col-lg-3 py-2 text-white">
        <h2>FREE UPDATES</h2>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Email" aria-label="Email">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Update me!</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="sidebar" style="background-image: url(<%= image_path "flower_vertical.jpg"%>)">
  <div class="pl-2">
    <%= link_to index_path do %>
      <%= image_tag "logo.png", alt: "Phung Consulting Logo", class:"pt-3 pl-xl-5 ml-xl-4 pl-lg-5 ml-lg-4 pl-md-2 ml-md-2 pl-sm-2 ml-sm-2" %>
    <% end %>
    <div class="sidebar-links pl-xl-5 ml-xl-4 pl-lg-5 ml-lg-4 pl-md-2 ml-md-2 pl-sm-2 ml-sm-2">
      <div class="selectors">
        <div id="root-selector" class="selector"> <p class="sidebar-link" ><%= link_to "accueil", root_path, class:"sidebar-link" %></p> </div>
        <div id="societe-selector" class="selector active"> <p class="sidebar-link" >la société</p> </div>
        <div id="activites-selector" class="selector"> <p class="sidebar-link" >activités</p> </div>
        <div id="references-selector" class="selector"> <p class="sidebar-link" >références</p> </div>
        <div id="evenements-selector" class="selector"> <p class="sidebar-link" >événements</p> </div>
        <div id="documents-selector" class="selector"> <p class="sidebar-link" >documents</p> </div>
        <div id="about-us-selector" class="selector"> <p class="sidebar-link" >🇬🇧 about us</p> </div>
        <div id="contact-selector" class="selector"> <p class="sidebar-link" >contact</p> </div>
      </div>
    </div>
  </div>
</div>

<!--
      <div id="root-selector" class="selector"> <p><#%= link_to "accueil", root_path, class:"sidebar-link" %></p> </div>
      <div id="societe-selector" class="selector active"> <p><#%= link_to "la société", index_path, class:"sidebar-link" %></p> </div>
      <div id="activites-selector" class="selector"> <p><#%= link_to "activités", activites_path, class:"sidebar-link" %></p> </div>
      <div id="references-selector" class="selector"> <p><#%= link_to "références", references_path, class:"sidebar-link" %></p> </div>
      <div id="evenements-selector" class="selector"> <p><#%= link_to "événements", evenements_path, class:"sidebar-link" %></p> </div>
      <div id="documents-selector" class="selector"> <p><#%= link_to "documents", documents_path, class:"sidebar-link" %></p> </div>
      <div id="about-us-selector" class="selector"> <p><#%= link_to "🇬🇧 about us", about_us_path, class:"sidebar-link" %></p> </div>
      <div id="contact-selector" class="selector"> <p><#%= link_to "contact", contact_path, class:"sidebar-link" %></p> </div> -->

app/views/shared/_social-links.html.erb
<div class="py-4" style="background-color: #F53045">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6 text-center">
      <%= link_to "#",target:"_blank" do  %>
        <i class="fab fa-instagram social-link-icon"></i>
      <% end %>
      <%= link_to "#",target:"_blank" do  %>
        <i class="fab fa-facebook social-link-icon"></i>
      <% end %>
      <%= link_to "#",target:"_blank" do  %>
        <i class="fab fa-twitter social-link-icon"></i>
      <% end %>
      <%= link_to "#",target:"_blank" do  %>
        <i class="fab fa-linkedin social-link-icon"></i>
      <% end %>
      <%= link_to "#",target:"_blank" do  %>
        <i class="fas fa-rss social-link-icon"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_vertical-card.html.erb
<div class="card m-3" style="width: 18rem;">
  <img class="card-img-top" src="<%= @url_image_path %>" alt="Card image cap">
  <div class="card-body">
    <p class="card-text"><b>Title card </b></p>
    <p class="card-text">Some quick example of card text </p>
  </div>
</div>